language: python
python:
  - 2.7
dist: 
  - xenial
services:
  - xvfb
install:
  - sudo apt-get install cmake xorg-dev libglu1-mesa-dev texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended pandoc imagemagick libglfw3-dev git-core
  - # Install glfw
  - git clone https://github.com/glfw/glfw.git ~/glfw
  - cd ~/glfw
  - cmake .
  - make
  - sudo make install
  - cd -
  - # Install glslViewer
  - git clone http://github.com/patriciogonzalezvivo/glslViewer ~/glslViewer
  - cd ~/glslViewer
  - make
  - sudo make install
  - cd -
before_script:
  - #export DISPLAY=:99.0
  - #xvfb-run
  - #sleep 3 # give xvfb some time to start
  - #rm -rf 12 13 14 15 16 17 18 # ugly ...
script:
  - travis_wait make
  - ls
deploy:
  provider: releases
  api_key: $GH_REPO_TOKEN
  file: "book.pdf"
  skip_cleanup: true
